#!/usr/bin/env bash
# check-github-issue-sync.sh — GitHub-issue-sync structural invariant (issue-11)
#
# Scans every folder under knowledge/issues/*/ and knowledge/enhancements/*/,
# reads each spec's frontmatter github_issue / github-issue field (both spellings
# normalized — this codebase uses underscore in enhancements/, hyphen in issues/),
# and classifies each folder:
#   OK       — a real issue reference (bare number or #NNN)
#   PENDING  — github_issue: pending (in-flight draft; advisory, never a failure)
#   GAP      — missing / null / "#N" / "TBD" placeholder
# A GAP whose folder is listed in the baseline file is an EXEMPT historical gap
# (issue-11 Cause 1: ENH-013-022; Cause 2: ENH-024+). A GAP NOT in the baseline
# is a NEW LEAK — the invariant this check enforces going forward.
#
# Modes:
#   (default)            report: human-readable summary; exit 1 if any new leak (CI-friendly).
#   --generate-baseline  snapshot current GAP folders into the baseline file, exit 0.
#   --findings           print only new-leak (+ pending advisory) lines to stdout,
#                        always exit 0. Consumed by pre-push-gate.sh (Gate 4).
#
# Pure read (no network, no writes) except in --generate-baseline mode.

set -euo pipefail

REPO_ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
BASELINE_FILE="${REPO_ROOT}/scripts/.github-issue-sync-baseline.txt"

MODE="report"
case "${1:-}" in
  --generate-baseline) MODE="baseline" ;;
  --findings)          MODE="findings" ;;
  "")                  MODE="report" ;;
  *) echo "usage: $(basename "$0") [--generate-baseline|--findings]" >&2; exit 2 ;;
esac

# Locate the spec file inside an artifact folder (specification.md or description.md).
spec_file_for() {
  local dir="$1" f
  for f in "$dir"/*-specification.md "$dir"/*-description.md; do
    [ -f "$f" ] && { printf '%s\n' "$f"; return 0; }
  done
  return 1
}

# Read + normalize the github_issue / github-issue value → OK | PENDING | GAP.
classify_spec() {
  local spec="$1" raw val
  raw=$(grep -iE '^[[:space:]]*github[_-]issue[[:space:]]*:' "$spec" 2>/dev/null | head -1 || true)
  [ -z "$raw" ] && { printf 'GAP\n'; return; }
  val=$(printf '%s' "$raw" \
    | sed -E 's/^[[:space:]]*github[_-]issue[[:space:]]*:[[:space:]]*//; s/^["'\'']//; s/["'\'']$//; s/[[:space:]]+$//')
  case "$val" in
    ""|null|Null|NULL|"~"|"#N"|N|TBD|tbd|"#TBD") printf 'GAP\n' ;;
    pending|Pending|PENDING)                      printf 'PENDING\n' ;;
    *)                                            printf 'OK\n' ;;
  esac
}

# Walk artifact folders; collect repo-relative GAP and PENDING folder paths.
GAPS=()
PENDINGS=()
while IFS= read -r dir; do
  [ -d "$dir" ] || continue
  spec=$(spec_file_for "$dir") || continue   # non-spec folders are out of scope
  case "$(classify_spec "$spec")" in
    GAP)     GAPS+=("${dir#"$REPO_ROOT"/}") ;;
    PENDING) PENDINGS+=("${dir#"$REPO_ROOT"/}") ;;
    OK)      : ;;
  esac
done < <(find "${REPO_ROOT}/knowledge/issues" "${REPO_ROOT}/knowledge/enhancements" \
              -mindepth 1 -maxdepth 1 -type d 2>/dev/null | sort)

# --generate-baseline: snapshot current GAP folders as documented exemptions.
if [ "$MODE" = "baseline" ]; then
  {
    printf '# github-issue-sync baseline — folders with a documented historical gap (issue-11).\n'
    printf '# Generated by: scripts/check-github-issue-sync.sh --generate-baseline\n'
    printf '# Folders listed here are EXEMPT from the sync invariant (pre-existing gaps:\n'
    printf '# Cause 1 = ENH-013-022, Cause 2 = ENH-024+). Folders created AFTER this snapshot\n'
    printf '# are NOT exempt and hard-fail the check if they lack a real github_issue.\n'
    printf '# Do NOT hand-add a folder here to silence a new leak — fix the leak instead.\n'
    [ "${#GAPS[@]}" -gt 0 ] && printf '%s\n' "${GAPS[@]}"
  } > "$BASELINE_FILE"
  echo "Wrote baseline: ${BASELINE_FILE} (${#GAPS[@]} exempted folders)"
  exit 0
fi

# Partition GAPs into baseline-exempt vs new leaks.
is_exempt() {
  [ -f "$BASELINE_FILE" ] || return 1
  grep -qxF "$1" "$BASELINE_FILE"
}
NEW_LEAKS=()
EXEMPT_GAPS=()
if [ "${#GAPS[@]}" -gt 0 ]; then
  for folder in "${GAPS[@]}"; do
    if is_exempt "$folder"; then EXEMPT_GAPS+=("$folder"); else NEW_LEAKS+=("$folder"); fi
  done
fi

# --findings: text consumed by pre-push-gate.sh (Gate 4). Always exit 0.
if [ "$MODE" = "findings" ]; then
  if [ "${#NEW_LEAKS[@]}" -gt 0 ]; then
    printf 'STOP: github-issue-sync — %d folder(s) lack a real github_issue and are not in the ship-time baseline:\n' "${#NEW_LEAKS[@]}"
    printf '  - %s\n' "${NEW_LEAKS[@]}"
    printf 'Run /kmgraph:kmg-start-issue-tracking to create the GitHub issue, or set github_issue: pending if still drafting.\n'
  fi
  if [ "${#PENDINGS[@]}" -gt 0 ]; then
    printf 'AWAITING SYNC: %d draft folder(s) marked github_issue: pending (informational, not a failure):\n' "${#PENDINGS[@]}"
    printf '  - %s\n' "${PENDINGS[@]}"
  fi
  exit 0
fi

# Default report mode (CI/standalone).
echo "github-issue-sync invariant (issue-11)"
echo "  exempt historical gaps : ${#EXEMPT_GAPS[@]}"
echo "  awaiting sync (pending): ${#PENDINGS[@]}"
echo "  NEW leaks              : ${#NEW_LEAKS[@]}"
if [ "${#PENDINGS[@]}" -gt 0 ]; then
  echo "-- awaiting sync --"; printf '  %s\n' "${PENDINGS[@]}"
fi
if [ "${#NEW_LEAKS[@]}" -gt 0 ]; then
  echo "-- NEW leaks (fix before shipping) --"; printf '  %s\n' "${NEW_LEAKS[@]}"
  exit 1
fi
echo "OK: no new github-issue-sync leaks."
exit 0
