/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Knowledge Management Graph",
  "tagline": "Structured knowledge capture and cross-session memory for Claude Code projects.",
  "favicon": "img/square.png",
  "url": "https://technomensch.github.io",
  "baseUrl": "/knowledge-graph/",
  "organizationName": "technomensch",
  "projectName": "knowledge-graph",
  "trailingSlash": true,
  "onBrokenLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "themes": [
    "@docusaurus/theme-mermaid"
  ],
  "markdown": {
    "mermaid": true,
    "format": "detect",
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "plugins": [
    [
      "@docusaurus/plugin-client-redirects",
      {
        "redirects": []
      }
    ],
    [
      "@docusaurus/plugin-content-blog",
      {
        "id": "docs-updates",
        "routeBasePath": "docs-updates",
        "path": "./docs-updates",
        "blogTitle": "Documentation Updates",
        "blogDescription": "Changes to the KMGraph documentation site",
        "showReadingTime": false,
        "feedOptions": {
          "type": [
            "rss",
            "atom"
          ],
          "title": "KMGraph Docs Updates"
        },
        "blogSidebarCount": "ALL"
      }
    ],
    "plugin-image-zoom",
    [
      "@orama/plugin-docusaurus-v3",
      {
        "analytics": {
          "enabled": false
        }
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/mkaplan/GitHub/knowledge-graph/sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/technomensch/knowledge-graph/edit/main/",
          "exclude": [
            "plans/**",
            "chat-history/**",
            "sessions/**",
            "_test-layout.md"
          ]
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/mkaplan/GitHub/knowledge-graph/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "mermaid": {
      "theme": {
        "light": "neutral",
        "dark": "dark"
      },
      "options": {}
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "KMGraph",
      "logo": {
        "alt": "Staying in Sync",
        "src": "img/avatar.png"
      },
      "items": [
        {
          "to": "/GETTING-STARTED",
          "label": "Getting Started",
          "position": "left"
        },
        {
          "to": "/CONCEPTS",
          "label": "Concepts",
          "position": "left"
        },
        {
          "to": "/COMMAND-GUIDE",
          "label": "Commands",
          "position": "left"
        },
        {
          "to": "/CONFIGURATION",
          "label": "Configuration",
          "position": "left"
        },
        {
          "href": "https://github.com/technomensch/knowledge-graph",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        },
        {
          "href": "https://www.linkedin.com/in/marckaplan/",
          "position": "right",
          "className": "header-linkedin-link",
          "aria-label": "LinkedIn profile"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "logo": {
        "alt": "Staying in Sync",
        "src": "img/banner.jpeg",
        "href": "https://github.com/technomensch/knowledge-graph",
        "width": 160
      },
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Getting Started",
              "to": "/GETTING-STARTED"
            },
            {
              "label": "Command Guide",
              "to": "/COMMAND-GUIDE"
            },
            {
              "label": "Cheat Sheet",
              "to": "/CHEAT-SHEET"
            },
            {
              "label": "FAQ",
              "to": "/FAQ"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/technomensch/knowledge-graph"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/marckaplan/"
            },
            {
              "label": "Buy Me a Coffee",
              "href": "https://buymeacoffee.com/technomensch"
            }
          ]
        }
      ],
      "copyright": "Staying in Sync"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
